name: Deploy Pipeline
on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
env:
  ENVIRONMENT: "production"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Verify artifact integrity
        run: |
          sha256sum -c checksum.txt

      - name: Authenticate to Vault (OIDC)
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: ${{ secrets.VAULT_URL }}
          method: jwt
          role: github-actions-role
        id: vault

      - name: Retrieve secrets from Vault
        run: |
          vault kv get -field=value secret/data/prod/api-key > api_key.txt
        env:
          VAULT_TOKEN: ${{ steps.vault.outputs.vault_token }}

      - name: Deploy (simulated)
        run: |
          echo "Deploying version $GITHUB_SHA to $ENVIRONMENT environment..."
          echo "Using API_KEY=$(cat api_key.txt) to connect to production service"
