name: CI Pipeline
on:
  push:
    branches: ["*", "!main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/

      - name: Lint code
        run: |
          pip install flake8 && flake8 .

      - name: Secret scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-git --verbose --redact --exit-code=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build artifact
        run: |
          zip -r demo-app.zip .

      - name: Compute artifact checksum
        id: checksum
        run: |
          sha256sum demo-app.zip > checksum.txt

      - name: Upload artifact & checksum
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            demo-app.zip
            checksum.txt
